### ISSUE TITLE
ED Fernández Luna Ma. Guadalupe 

### ISSUE THREAD

**Issue by Aalxnder** [lordfriky/grupos_icom#63]
### Enlace de invitación

https://chat.whatsapp.com/BoGuj5BidQM6qqweBGuuvE

### Clave de la materia

IL347

### NRC del curso

197381

**Comment by Aalxnder** [comment]
Grupo para ED con Fernández Luna Ma. Guadalupe

**Comment by lordfriky** [comment]
Evita cambiarle el nombre al issue porque sino el bot no puede tomarlo en cuenta, igual el link ya fue agregado (#64).
