### ISSUE TITLE
bot|I5289|195114|<link_al_grupo_de_whatsapp>

### ISSUE THREAD

**Issue by Spellman66** [lordfriky/grupos_icom#7]
Sólo cambia `<link_al_grupo_de_whatsapp>` en el título por el link correspondiente y haz clic en `Submit new issue`. Los cambios deberían verse reflejados de 30 a 60 segundos. Si el link no se actualiza contáctame por WhatsApp.

**Comment by lordfriky** [comment]
Tienes que cambiar lo que dice `<link_al_grupo_de_whatsapp>` en el título por el link que le quieras poner
